import { FormEvent, useEffect, useState } from "react";

import { portfolioClient, type PortfolioClient, type PortfolioResponse, type TradePreviewBody, type TradePreviewResponse } from "./client";
import type { PortfolioMutationPreviewResponse } from "../generated/api";

interface ImpactSummaryValue {
  subject?: unknown;
  action_label?: unknown;
  before?: Record<string, unknown>;
  after?: Record<string, unknown>;
  consequences?: unknown[];
  confirmation_verb?: unknown;
}

function ImpactSummary({ value }: { value: unknown }) {
  const summary = value && typeof value === "object" ? value as ImpactSummaryValue : {};
  const entries = (record: Record<string, unknown> | undefined) => Object.entries(record ?? {});
  return <section className="portfolio-impact" aria-label="操作影響摘要">
    <h3>{String(summary.action_label ?? "確認操作")}</h3>
    <p>目標：{String(summary.subject ?? "投資組合")}</p>
    <dl><div><dt>變更前</dt><dd>{entries(summary.before).map(([key, item]) => `${key}: ${String(item)}`).join("、") || "—"}</dd></div><div><dt>變更後</dt><dd>{entries(summary.after).map(([key, item]) => `${key}: ${String(item)}`).join("、") || "—"}</dd></div></dl>
    <ul>{(summary.consequences ?? []).map((item, index) => <li key={index}>{String(item)}</li>)}</ul>
  </section>;
}

function ExposureGroup({ title, values }: { title: string; values?: Record<string, string> }) {
  const entries = Object.entries(values ?? {});
  return <section className="exposure-group"><h3>{title}</h3>{entries.length ? <dl>{entries.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{new Intl.NumberFormat("zh-TW", { style: "percent", maximumFractionDigits: 2 }).format(Number(value))}</dd></div>)}</dl> : <p>目前無曝險。</p>}</section>;
}

export function PortfolioRoutes({ client = portfolioClient, companyId }: { client?: PortfolioClient; companyId?: string }) {
  const [portfolio, setPortfolio] = useState<PortfolioResponse | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [buyRate, setBuyRate] = useState("0.001425"); const [minBuy, setMinBuy] = useState("20"); const [sellRate, setSellRate] = useState("0.001425"); const [minSell, setMinSell] = useState("20"); const [taxRate, setTaxRate] = useState("0.003");
  const [cash, setCash] = useState("100000"); const [reason, setReason] = useState("");
  const [security, setSecurity] = useState(companyId ?? "2330"); const [side, setSide] = useState<"buy" | "sell">("buy"); const [quantity, setQuantity] = useState("1"); const [price, setPrice] = useState("100"); const [fees, setFees] = useState("0"); const [tax, setTax] = useState("0"); const [allocations, setAllocations] = useState("independent,1"); const [tradeReason, setTradeReason] = useState(""); const [pending, setPending] = useState<{ preview: TradePreviewResponse; input: TradePreviewBody } | null>(null);
  const [tradeSource, setTradeSource] = useState<{ kind: "manual" | "csv"; rowId: string; brokerReference: string | null; executedAt: string } | null>(null);
  const [csv, setCsv] = useState("source_row_id,broker_reference,security_id,side,quantity,price,fees,tax,executed_at\nrow-1,,2330,buy,1,100,0,0,2026-08-29T05:00:00+00:00"); const [csvResult, setCsvResult] = useState<{ trades: Record<string, unknown>[]; issues: Record<string, unknown>[] } | null>(null);
  const [correctionTradeId, setCorrectionTradeId] = useState(""); const [correctionReason, setCorrectionReason] = useState(""); const [correctionPending, setCorrectionPending] = useState<PortfolioMutationPreviewResponse | null>(null);
  const [actionKind, setActionKind] = useState<"split"|"capital_reduction"|"stock_dividend">("split"); const [postShares, setPostShares] = useState("2"); const [cashInLieu, setCashInLieu] = useState("0"); const [actionReason, setActionReason] = useState(""); const [actionPending, setActionPending] = useState<PortfolioMutationPreviewResponse | null>(null);
  useEffect(() => { let active = true; client.get().then((value) => active && setPortfolio(value)).catch(() => undefined); return () => { active = false; }; }, [client]);
  const saveCosts = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { setPortfolio(await client.saveCostProfile({ expected_version: portfolio?.version ?? 0, buy_rate: buyRate, minimum_buy_fee: minBuy, sell_rate: sellRate, minimum_sell_fee: minSell, tax_rate: taxRate, effective_at: new Date().toISOString(), reason: reason.trim(), idempotency_key: crypto.randomUUID() })); setReason(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "儲存失敗"); } finally { setBusy(false); } };
  const saveCash = async (event: FormEvent) => { event.preventDefault(); if (!portfolio) return; setBusy(true); setError(""); try { setPortfolio(await client.saveCash({ expected_version: portfolio.version, cash, as_of: new Date().toISOString(), reason: reason.trim(), idempotency_key: crypto.randomUUID() })); setReason(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "儲存失敗"); } finally { setBusy(false); } };
  const tradeInput = (): TradePreviewBody => ({ expected_version: portfolio?.version ?? 0, source_kind: tradeSource?.kind ?? "manual", source_row_id: tradeSource?.rowId ?? crypto.randomUUID(), broker_reference: tradeSource?.brokerReference ?? null, security_id: security.trim(), side, quantity: Number(quantity), price, fees, tax, executed_at: tradeSource?.executedAt ?? new Date().toISOString(), allocations: allocations.split("\n").filter((line) => line.trim()).map((line) => { const [bucket_id, allocated] = line.split(",").map((value) => value.trim()); return { bucket_id, quantity: Number(allocated) }; }) });
  const previewTrade = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const input = tradeInput(); setPending({ input, preview: await client.previewTrade(input) }); } catch (caught) { setError(caught instanceof Error ? caught.message : "預覽失敗"); } finally { setBusy(false); } };
  const confirmTrade = async () => { if (!pending || !tradeReason.trim()) return; setBusy(true); setError(""); try { setPortfolio(await client.confirmTrade({ ...pending.input, challenge_token: pending.preview.challenge_token, reason: tradeReason.trim(), idempotency_key: crypto.randomUUID() })); setPending(null); setTradeReason(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "確認失敗，請重新預覽"); } finally { setBusy(false); } };
  const previewCsv = async () => { setBusy(true); setError(""); try { setCsvResult(await client.previewCsv(csv)); } catch (caught) { setError(caught instanceof Error ? caught.message : "CSV 預覽失敗"); } finally { setBusy(false); } };
  const loadCsvTrade = (value: Record<string, unknown>) => {
    setSecurity(String(value.security_id ?? "")); setSide(value.side === "sell" ? "sell" : "buy");
    setQuantity(String(value.quantity ?? "")); setPrice(String(value.price ?? ""));
    setFees(String(value.fees ?? "0")); setTax(String(value.tax ?? "0"));
    setAllocations(`independent,${String(value.quantity ?? "")}`);
    setTradeSource({ kind: "csv", rowId: String(value.source_row_id ?? ""), brokerReference: value.broker_reference == null ? null : String(value.broker_reference), executedAt: String(value.executed_at ?? "") });
    setPending(null);
  };
  const previewCorrection = async () => { if (!portfolio || !correctionTradeId) return; setBusy(true); setError(""); try { setCorrectionPending(await client.previewCorrection({ expected_version: portfolio.version, original_trade_id: correctionTradeId })); } catch (caught) { setError(caught instanceof Error ? caught.message : "更正預覽失敗"); } finally { setBusy(false); } };
  const confirmCorrection = async () => { if (!portfolio || !correctionPending || !correctionReason.trim()) return; setBusy(true); setError(""); try { setPortfolio(await client.confirmCorrection({ expected_version: correctionPending.target_version, original_trade_id: correctionTradeId, challenge_token: correctionPending.challenge_token, reason: correctionReason.trim(), idempotency_key: crypto.randomUUID() })); setCorrectionPending(null); setCorrectionReason(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "更正確認失敗，請重新預覽"); } finally { setBusy(false); } };
  const previewAction = async () => { if (!portfolio) return; setBusy(true); setError(""); try { setActionPending(await client.previewCompanyAction({ expected_version: portfolio.version, security_id: security.trim(), action_kind: actionKind, confirmed_post_action_shares: Number(postShares), cash_in_lieu: cashInLieu })); } catch (caught) { setError(caught instanceof Error ? caught.message : "公司行動預覽失敗"); } finally { setBusy(false); } };
  const confirmAction = async () => { if (!actionPending || !actionReason.trim()) return; setBusy(true); setError(""); try { setPortfolio(await client.confirmCompanyAction({ expected_version: actionPending.target_version, security_id: security.trim(), action_kind: actionKind, confirmed_post_action_shares: Number(postShares), cash_in_lieu: cashInLieu, challenge_token: actionPending.challenge_token, reason: actionReason.trim(), idempotency_key: crypto.randomUUID() })); setActionPending(null); setActionReason(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "公司行動確認失敗，請重新預覽"); } finally { setBusy(false); } };
  const exposure = portfolio?.exposure as { nav?: string; feasible?: boolean; reasons?: string[]; security_exposure?: Record<string,string>; industry_exposure?: Record<string,string>; theme_exposure?: Record<string,string> } | undefined;
  const visibleHoldings = portfolio?.holdings.filter((value) => !companyId || String(value.security_id) === companyId) ?? [];
  const visibleTrades = portfolio?.trades.filter((value) => !companyId || String(value.security_id) === companyId) ?? [];
  return <main className="portfolio-page"><header className="company-header"><div><p className="eyebrow">{companyId ? "Company workspace · Trades" : "Owner workspace"}</p><h1>{companyId ? `${companyId} · 交易` : "投資組合與交易"}</h1></div>{companyId ? <nav aria-label="公司工作區"><a href={`/companies/${encodeURIComponent(companyId)}`}>Evidence</a><a href={`/companies/${encodeURIComponent(companyId)}/theses`}>Theses</a><a aria-current="page" href={`/companies/${encodeURIComponent(companyId)}/trades`}>Trades</a></nav> : <a href="/">返回公司研究</a>}</header>{error && <p className="error-banner" role="alert">{error}</p>}
    <div className="portfolio-grid"><form className="panel" onSubmit={saveCosts}><h2>1. 成本設定</h2><div className="field-row"><label>買進費率<input required value={buyRate} onChange={(e) => setBuyRate(e.target.value)} /></label><label>最低買進費<input required value={minBuy} onChange={(e) => setMinBuy(e.target.value)} /></label><label>賣出費率<input required value={sellRate} onChange={(e) => setSellRate(e.target.value)} /></label><label>最低賣出費<input required value={minSell} onChange={(e) => setMinSell(e.target.value)} /></label><label>證交稅率<input required value={taxRate} onChange={(e) => setTaxRate(e.target.value)} /></label></div><label>儲存理由<input required value={reason} onChange={(e) => setReason(e.target.value)} /></label><button className="primary-button" disabled={busy}>儲存成本版本</button></form>
    <form className="panel" onSubmit={saveCash}><h2>2. 可投資現金</h2><label>現金<input required value={cash} onChange={(e) => setCash(e.target.value)} /></label><label>儲存理由<input required value={reason} onChange={(e) => setReason(e.target.value)} /></label><button className="primary-button" disabled={!portfolio || busy}>儲存現金版本</button></form>
    <section className="panel exposure-panel"><h2>目前曝險</h2><p>NAV：{exposure?.nav ?? "尚未計算"} · {exposure?.feasible ? "符合 hard caps" : "尚不可行"}</p>{exposure?.reasons?.length ? <ul>{exposure.reasons.map((value) => <li key={value}>{value}</li>)}</ul> : null}<div className="exposure-groups"><ExposureGroup title="證券曝險" values={exposure?.security_exposure} /><ExposureGroup title="產業曝險" values={exposure?.industry_exposure} /><ExposureGroup title="主題曝險" values={exposure?.theme_exposure} /></div><p>Portfolio v{portfolio?.version ?? 0}</p></section></div>
    <form className="panel trade-form" onSubmit={previewTrade}><h2>3. 手動交易預覽</h2><p className="field-help">官方收盤價、產業與已確認風險主題由伺服器取得；預覽不會寫入交易。</p><div className="field-row"><label>證券代號<input required value={security} onChange={(e) => setSecurity(e.target.value)} /></label><label>方向<select value={side} onChange={(e) => setSide(e.target.value as "buy"|"sell")}><option value="buy">買進</option><option value="sell">賣出</option></select></label><label>股數<input required type="number" min="1" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></label><label>成交價<input required value={price} onChange={(e) => setPrice(e.target.value)} /></label><label>手續費<input required value={fees} onChange={(e) => setFees(e.target.value)} /></label><label>交易稅<input required value={tax} onChange={(e) => setTax(e.target.value)} /></label></div><label>分配桶（每行：bucket ID,股數）<textarea required value={allocations} onChange={(e) => setAllocations(e.target.value)} /></label><p className="field-help">可分配到多個 active Thesis 或 independent；各行股數合計必須等於成交股數，伺服器會再次驗證。</p><button className="primary-button" disabled={!portfolio?.cash_as_of || busy}>預覽交易與風控</button></form>
    <section className="panel"><h2>Canonical CSV 預覽</h2><p className="field-help">先驗證固定欄位與檔案內重複；每一筆合法交易仍須帶入上方，經伺服器風控預覽與你的明確確認後才會寫入。</p><label>CSV 內容<textarea value={csv} onChange={(event) => setCsv(event.target.value)} /></label><button type="button" className="secondary-button" disabled={busy} onClick={() => void previewCsv()}>驗證 CSV</button>{csvResult && <p aria-live="polite">合法 {csvResult.trades.length} 筆；問題 {csvResult.issues.length} 筆。</p>}{csvResult?.trades.length ? <ol className="csv-trade-list">{csvResult.trades.map((value, index) => <li key={`${String(value.source_row_id)}-${index}`}><span>{String(value.security_id)} · {String(value.side)} {String(value.quantity)} 股</span><button type="button" className="secondary-button" onClick={() => loadCsvTrade(value)}>帶入第 {index + 1} 筆交易</button></li>)}</ol> : null}{csvResult?.issues.length ? <pre>{JSON.stringify(csvResult.issues, null, 2)}</pre> : null}</section>
    <section className="panel"><h2>持股與交易紀錄</h2>{visibleHoldings.length ? <ul>{visibleHoldings.map((value, index) => <li key={index}>{String(value.security_id)} · {String(value.bucket_id)} · {String(value.quantity)} 股 · 官方價日 {String(value.price_date)}</li>)}</ul> : <p>尚無持股。</p>}{visibleTrades.length ? <ul>{visibleTrades.map((value) => <li key={String(value.trade_id)}>{String(value.trade_id)} · {String(value.security_id)} · {String(value.side)} {String(value.quantity)} 股</li>)}</ul> : null}</section>
    <div className="portfolio-grid"><section className="panel"><h2>追加交易更正</h2><p className="field-help">原交易保持不可變；確認後追加反向紀錄。</p><label>原交易 ID<select value={correctionTradeId} onChange={(event) => setCorrectionTradeId(event.target.value)}><option value="">請選擇</option>{visibleTrades.map((value) => <option key={String(value.trade_id)} value={String(value.trade_id)}>{String(value.trade_id)}</option>)}</select></label><button className="secondary-button" disabled={!correctionTradeId || busy} onClick={() => void previewCorrection()}>預覽反向更正</button></section><section className="panel"><h2>公司行動</h2><div className="field-row"><label>類型<select value={actionKind} onChange={(event) => setActionKind(event.target.value as typeof actionKind)}><option value="split">股票分割</option><option value="capital_reduction">減資</option><option value="stock_dividend">股票股利</option></select></label><label>券商確認後總股數<input type="number" min="0" value={postShares} onChange={(event) => setPostShares(event.target.value)} /></label><label>現金替代款<input value={cashInLieu} onChange={(event) => setCashInLieu(event.target.value)} /></label></div><button className="secondary-button" disabled={!visibleHoldings.length || busy} onClick={() => void previewAction()}>預覽公司行動</button></section></div>
    {pending && <div className="dialog-backdrop" role="presentation"><section className="confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="trade-confirmation-title"><h2 id="trade-confirmation-title">確認交易與桶分配</h2><ImpactSummary value={pending.preview.impact_summary} /><p>交易後現金 {pending.preview.post_cash}，NAV {pending.preview.nav}</p><p>{pending.preview.feasible ? "符合伺服器 hard caps" : pending.preview.reasons.join("、")}</p><label>確認理由<input value={tradeReason} onChange={(e) => setTradeReason(e.target.value)} /></label><div className="dialog-actions"><button onClick={() => setPending(null)}>取消</button><button className="danger-button" disabled={!tradeReason.trim() || busy} onClick={() => void confirmTrade()}>確認交易</button></div></section></div>}
    {correctionPending && <div className="dialog-backdrop" role="presentation"><section className="confirmation-dialog" role="dialog" aria-modal="true" aria-label="確認交易更正"><h2>確認交易更正</h2><ImpactSummary value={correctionPending.impact_summary} /><p>更正後現金 {correctionPending.post_cash}</p><label>更正理由<input value={correctionReason} onChange={(event) => setCorrectionReason(event.target.value)} /></label><div className="dialog-actions"><button onClick={() => setCorrectionPending(null)}>取消</button><button className="danger-button" disabled={!correctionReason.trim() || busy} onClick={() => void confirmCorrection()}>確認追加更正</button></div></section></div>}
    {actionPending && <div className="dialog-backdrop" role="presentation"><section className="confirmation-dialog" role="dialog" aria-modal="true" aria-label="確認公司行動"><h2>確認公司行動</h2><ImpactSummary value={actionPending.impact_summary} /><dl className="allocation-summary">{Object.entries((actionPending.allocation?.shares as Record<string, unknown> | undefined) ?? {}).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)} 股</dd></div>)}</dl><label>確認理由<input value={actionReason} onChange={(event) => setActionReason(event.target.value)} /></label><div className="dialog-actions"><button onClick={() => setActionPending(null)}>取消</button><button className="danger-button" disabled={!actionReason.trim() || busy} onClick={() => void confirmAction()}>確認公司行動</button></div></section></div>}
  </main>;
}
