"""Validate architecture-adoption inputs and reconcile approved legacy debt."""

from __future__ import annotations

import re
import json
from datetime import date
from pathlib import Path
from typing import Any


SCHEMA_VERSION = "2.2.0"
SUPPORTED_SCHEMA_VERSIONS = {"2.1.0", SCHEMA_VERSION}
BANNED_AI_APPROVERS = {"ai", "assistant", "chatgpt", "codex", "gpt", "model", "openai"}
BASELINE_REQUIRED_FIELDS = {
    "rule_id",
    "location",
    "rationale",
    "approved_by",
    "approval_date",
    "approval_reference",
    "captured_revision",
    "review_by",
    "removal_condition",
}
GENERATED_MARKER = "<!-- GENERATED BY govern-modular-event-architecture; DO NOT EDIT -->"
JSON_GENERATED_MARKER = "GENERATED BY govern-modular-event-architecture; DO NOT EDIT"


def _diagnostic(
    rule_id: str,
    location: str,
    message: str,
    *,
    configuration: bool = True,
) -> dict[str, Any]:
    return {
        "rule_id": rule_id,
        "severity": "MUST",
        "location": location,
        "message": message,
        "configuration": configuration,
        "disposition": "active",
    }


def _human(value: Any) -> bool:
    words = set(re.findall(r"[a-z]+", str(value).lower()))
    return bool(str(value).strip()) and not words.intersection(BANNED_AI_APPROVERS)


def validate_adoption(
    manifest: dict[str, Any], adoption: dict[str, Any] | None
) -> list[dict[str, Any]]:
    diagnostics: list[dict[str, Any]] = []
    roots = manifest.get("composition_roots")
    if not isinstance(roots, list) or not roots:
        diagnostics.append(
            _diagnostic(
                "CMP001",
                "composition_roots",
                "at least one verifiable composition root is required",
            )
        )
    if adoption is None:
        diagnostics.append(
            _diagnostic(
                "ADP001",
                "architecture/adoption.yaml",
                "development and release gates require an adoption contract",
            )
        )
        return diagnostics
    expected_version = manifest.get("schema_version")
    if (
        adoption.get("schema_version") != expected_version
        or expected_version not in SUPPORTED_SCHEMA_VERSIONS
    ):
        diagnostics.append(
            _diagnostic(
                "ADP002",
                "schema_version",
                f"adoption schema must equal manifest schema {expected_version!r}",
            )
        )
    if adoption.get("project_stage") not in {"new", "existing"}:
        diagnostics.append(
            _diagnostic(
                "ADP003", "project_stage", "must be 'new' or 'existing'"
            )
        )
    analyzers = adoption.get("applicable_analyzers")
    if not isinstance(analyzers, list) or any(
        item not in {"python", "typescript", "c-cpp"} for item in analyzers
    ):
        diagnostics.append(
            _diagnostic(
                "ADP004",
                "applicable_analyzers",
                "must list only installed analyzers: python, typescript, and/or c-cpp",
            )
        )
    runtime = adoption.get("runtime_validation")
    if not isinstance(runtime, dict) or runtime.get("applicability") not in {
        "required",
        "not-applicable",
    }:
        diagnostics.append(
            _diagnostic(
                "VAL001",
                "runtime_validation",
                "must declare required or not-applicable",
            )
        )
    elif runtime.get("applicability") == "not-applicable" and not str(
        runtime.get("rationale", "")
    ).strip():
        diagnostics.append(
            _diagnostic(
                "VAL001",
                "runtime_validation.rationale",
                "not-applicable runtime validation requires a rationale",
            )
        )
    realtime = any(
        item.get("timing_class") in {"hard-real-time", "soft-real-time"}
        for item in manifest.get("workloads", [])
        if isinstance(item, dict)
    )
    scoped_runtime = any(
        scope in {"performance", "real-time"}
        for profile in manifest.get("execution_profiles", [])
        if isinstance(profile, dict)
        for scope in profile.get("assurance_scope", [])
    )
    if (
        isinstance(runtime, dict)
        and runtime.get("applicability") == "not-applicable"
        and (realtime or scoped_runtime)
    ):
        diagnostics.append(
            _diagnostic(
                "VAL002",
                "runtime_validation",
                "performance or real-time assurance requires runtime validation",
                configuration=False,
            )
        )
    host = adoption.get("tool_host_evidence")
    if not isinstance(host, dict):
        diagnostics.append(
            _diagnostic(
                "ADP005",
                "tool_host_evidence",
                "tool-host OS and Python compatibility metadata is required",
            )
        )
    remediation_items = adoption.get("remediation_items", [])
    if not isinstance(remediation_items, list):
        diagnostics.append(
            _diagnostic(
                "ADP006",
                "remediation_items",
                "must be a list",
            )
        )
    else:
        for index, item in enumerate(remediation_items):
            location = f"remediation_items[{index}]"
            if (
                not isinstance(item, dict)
                or item.get("status") not in {"DISCOVERED", "REMEDIATING"}
                or not str(item.get("issue", "")).strip()
                or not str(item.get("owner", "")).strip()
                or not str(item.get("completion_condition", "")).strip()
            ):
                diagnostics.append(
                    _diagnostic(
                        "ADP006",
                        location,
                        "unresolved remediation requires status, issue, owner, and completion condition",
                    )
                )
            else:
                diagnostics.append(
                    _diagnostic(
                        "ADP006",
                        location,
                        f"{item['status']}: {item['issue']}",
                        configuration=False,
                    )
                )
    return diagnostics


def _parse_baseline(
    baseline: dict[str, Any] | None,
    expected_schema_version: Any = SCHEMA_VERSION,
) -> tuple[dict[tuple[str, str], dict[str, Any]], list[dict[str, Any]]]:
    diagnostics: list[dict[str, Any]] = []
    entries: dict[tuple[str, str], dict[str, Any]] = {}
    if baseline is None:
        return entries, diagnostics
    if baseline.get("schema_version") != expected_schema_version:
        diagnostics.append(
            _diagnostic("BAS001", "baseline.schema_version", "baseline schema version mismatch")
        )
    violations = baseline.get("violations")
    if not isinstance(violations, list):
        diagnostics.append(
            _diagnostic("BAS002", "baseline.violations", "violations must be a list")
        )
        return entries, diagnostics
    for index, raw in enumerate(violations):
        location = f"baseline.violations[{index}]"
        if not isinstance(raw, dict) or any(
            not str(raw.get(field, "")).strip() for field in BASELINE_REQUIRED_FIELDS
        ):
            diagnostics.append(
                _diagnostic(
                    "BAS003",
                    location,
                    "temporary deferral requires exact rule/location, rationale, non-AI approval, revision, review date, and removal condition",
                )
            )
            continue
        if not _human(raw.get("approved_by")):
            diagnostics.append(
                _diagnostic(
                    "BAS003",
                    f"{location}.approved_by",
                    "temporary deferral requires a non-AI approver",
                )
            )
            continue
        try:
            review_by = date.fromisoformat(str(raw["review_by"]))
            date.fromisoformat(str(raw["approval_date"]))
        except ValueError:
            diagnostics.append(
                _diagnostic("BAS003", location, "approval_date and review_by must be ISO dates")
            )
            continue
        if review_by < date.today():
            diagnostics.append(
                _diagnostic("BAS007", location, "temporary deferral review date has expired")
            )
            continue
        key = (str(raw["rule_id"]), str(raw["location"]))
        if key in entries:
            diagnostics.append(
                _diagnostic("BAS003", location, "duplicate baseline rule/location")
            )
            continue
        entries[key] = raw
    return entries, diagnostics


def apply_baseline(
    diagnostics: list[dict[str, Any]],
    baseline: dict[str, Any] | None,
    previous_baseline: dict[str, Any] | None,
    *,
    phase: str,
    expected_schema_version: Any = SCHEMA_VERSION,
) -> list[dict[str, Any]]:
    """Apply exact approved deferrals and return baseline-policy diagnostics."""
    entries, policy = _parse_baseline(baseline, expected_schema_version)
    previous, previous_policy = _parse_baseline(
        previous_baseline, expected_schema_version
    )
    if previous_baseline is not None:
        policy.extend(previous_policy)
        for key in sorted(set(entries).difference(previous)):
            policy.append(
                _diagnostic(
                    "BAS004",
                    f"{key[0]}:{key[1]}",
                    "baseline growth is forbidden; remediate or obtain an accepted ADR",
                    configuration=False,
                )
            )
    if phase == "release" and entries:
        policy.append(
            _diagnostic(
                "BAS006",
                "architecture/baseline.yaml",
                "release requires a zero-entry temporary baseline",
                configuration=False,
            )
        )
        return policy
    active_keys = {
        (str(item.get("rule_id")), str(item.get("location")))
        for item in diagnostics
        if item.get("disposition", "active") == "active"
    }
    protected = {
        "ADP001",
        "ADP002",
        "ADP003",
        "ADP004",
        "ADP005",
        "BAS001",
        "BAS002",
        "BAS003",
        "BAS004",
        "BAS005",
        "BAS006",
        "BAS007",
    }
    if phase == "development":
        for item in diagnostics:
            key = (str(item.get("rule_id")), str(item.get("location")))
            if (
                key in entries
                and not item.get("configuration")
                and str(item.get("rule_id")) not in protected
                and not str(item.get("rule_id")).startswith("SCHED")
            ):
                item["disposition"] = "baseline"
    for key in sorted(set(entries).difference(active_keys)):
        policy.append(
            _diagnostic(
                "BAS005",
                f"{key[0]}:{key[1]}",
                "stale baseline entry no longer matches an active diagnostic",
                configuration=False,
            )
        )
    return policy


def readiness_status(
    diagnostics: list[dict[str, Any]], *, phase: str
) -> str:
    active = [item for item in diagnostics if item.get("disposition") == "active"]
    remediation = [
        item for item in active if item.get("rule_id") == "ADP006"
    ]
    if any("REMEDIATING:" in str(item.get("message")) for item in remediation):
        return "REMEDIATING"
    if any("DISCOVERED:" in str(item.get("message")) for item in remediation):
        return "DISCOVERED"
    if any(item.get("configuration") for item in active):
        return "BLOCKED"
    if any(item.get("severity") == "MUST" for item in active):
        return "FAIL"
    if any(item.get("disposition") == "baseline" for item in diagnostics):
        return "DEFERRED"
    return "VERIFIED"


def _stable_evidence(evidence: dict[str, Any]) -> dict[str, Any]:
    diagnostics = [
        {
            key: item.get(key)
            for key in (
                "rule_id",
                "severity",
                "location",
                "message",
                "configuration",
                "disposition",
            )
        }
        for item in evidence.get("diagnostics", [])
        if not str(item.get("rule_id", "")).startswith("DOC")
    ]
    active = [item for item in diagnostics if item.get("disposition") == "active"]
    if any(item.get("configuration") for item in active):
        code = 2
    elif any(
        item.get("severity") == "MUST" for item in active
    ):
        code = 1
    else:
        code = 0
    phase = "release-readiness"
    stable_analyzers: dict[str, Any] = {}
    for analyzer, raw_result in evidence.get("analyzers", {}).items():
        if not isinstance(raw_result, dict):
            continue
        result: dict[str, Any] = {"mode": raw_result.get("mode")}
        for field in ("analyzed_files", "covered_files"):
            values = raw_result.get(field)
            if isinstance(values, list):
                result[field] = sorted(str(value) for value in values)
        if isinstance(raw_result.get("worker_count"), int):
            result["worker_count"] = raw_result["worker_count"]
        if isinstance(raw_result.get("type_count"), int):
            result["type_count"] = raw_result["type_count"]
        toolchain = raw_result.get("toolchain")
        if isinstance(toolchain, dict):
            result["toolchain"] = {
                field: toolchain.get(field)
                for field in (
                    "provider",
                    "provider_version",
                    "binding_version",
                    "platform",
                    "archive_sha256",
                    "library_sha256",
                    "target_triple",
                    "clang_version",
                )
                if toolchain.get(field) is not None
            }
        stable_analyzers[str(analyzer)] = result
    return {
        "phase": phase,
        "gate_result": "PASS" if code == 0 else "BLOCKED",
        "readiness_status": readiness_status(diagnostics, phase=phase),
        "exit_code": code,
        "analyzers": stable_analyzers,
        "diagnostics": diagnostics,
    }


def render_adoption_documents(
    manifest: dict[str, Any],
    adoption: dict[str, Any],
    baseline: dict[str, Any] | None,
    evidence: dict[str, Any],
) -> dict[Path, str]:
    stable = _stable_evidence(evidence)
    roots = [
        item
        for item in manifest.get("composition_roots", [])
        if isinstance(item, dict)
    ]
    baseline_count = len((baseline or {}).get("violations", []))
    if baseline_count:
        stable["gate_result"] = "BLOCKED"
        stable["readiness_status"] = "FAIL"
        stable["exit_code"] = 1
    markdown = [
        GENERATED_MARKER,
        "",
        "# Architecture Adoption Readiness",
        "",
        f"- Project: `{manifest.get('project', {}).get('name', '')}`",
        f"- Phase: `{stable.get('phase')}`",
        f"- GateResult: `{stable.get('gate_result')}`",
        f"- Readiness: `{stable.get('readiness_status')}`",
        f"- Temporary baseline entries: `{baseline_count}`",
        "",
        "## Composition roots",
        "",
        "| ID | Kind | Module | Path | Symbol |",
        "|---|---|---|---|---|",
    ]
    for root in roots:
        markdown.append(
            f"| `{root.get('id')}` | `{root.get('kind')}` | `{root.get('module')}` | "
            f"`{root.get('path')}` | `{root.get('symbol')}` |"
        )
    markdown.extend(["", "## Source conformance", ""])
    for analyzer, result in sorted(stable.get("analyzers", {}).items()):
        files = ", ".join(result.get("analyzed_files", [])) or "n/a"
        markdown.append(
            f"- `{analyzer}`: `{result.get('mode')}`; files: {files}; "
            f"types: {result.get('type_count', 'n/a')}"
        )
    if not stable.get("analyzers"):
        markdown.append("- No analyzer evidence was produced.")
    markdown.extend(
        [
            "",
            "## Runtime-validation applicability",
            "",
            f"- Applicability: `{adoption.get('runtime_validation', {}).get('applicability')}`",
            f"- Rationale: {adoption.get('runtime_validation', {}).get('rationale', '')}",
            "",
            "## Diagnostics",
            "",
        ]
    )
    if stable["diagnostics"]:
        markdown.extend(
            f"- `{item['rule_id']}` `{item['location']}` — "
            f"`{item['disposition']}`: {item['message']}"
            for item in stable["diagnostics"]
        )
    else:
        markdown.append("- None.")
    markdown.extend(
        [
            "",
            "The manifest, analyzer evidence, baseline approvals, and accepted ADRs "
            "remain authoritative inputs. This report is a deterministic review projection.",
            "",
        ]
    )
    payload = {
        "_generated": JSON_GENERATED_MARKER,
        "schema_version": manifest.get("schema_version"),
        "project": manifest.get("project", {}).get("name"),
        "composition_roots": roots,
        "baseline_entry_count": baseline_count,
        "adoption": adoption,
        "evidence": stable,
    }
    return {
        Path("generated/adoption-readiness.md"): "\n".join(markdown),
        Path("generated/adoption-readiness.json"): json.dumps(
            payload, indent=2, ensure_ascii=False, sort_keys=True
        )
        + "\n",
    }


def compare_adoption_documents(
    manifest_path: Path,
    manifest: dict[str, Any],
    adoption: dict[str, Any],
    baseline: dict[str, Any] | None,
    evidence: dict[str, Any],
) -> list[dict[str, Any]]:
    expected = render_adoption_documents(manifest, adoption, baseline, evidence)
    root = manifest_path.parent
    diagnostics: list[dict[str, Any]] = []
    for relative, content in expected.items():
        destination = root / relative
        if not destination.is_file():
            diagnostics.append(
                _diagnostic(
                    "DOC001",
                    relative.as_posix(),
                    "generated adoption document is missing",
                    configuration=False,
                )
            )
        elif destination.read_text(encoding="utf-8") != content:
            diagnostics.append(
                _diagnostic(
                    "DOC002",
                    relative.as_posix(),
                    "generated adoption document is stale or manually changed",
                    configuration=False,
                )
            )
    generated_root = root / "generated"
    if generated_root.is_dir():
        for destination in generated_root.glob("adoption-readiness*"):
            if not destination.is_file() or destination.suffix not in {".md", ".json"}:
                continue
            relative = destination.relative_to(root)
            if relative not in expected:
                diagnostics.append(
                    _diagnostic(
                        "DOC003",
                        relative.as_posix(),
                        "obsolete generated adoption document exists",
                        configuration=False,
                    )
                )
    return diagnostics


def write_adoption_documents(
    manifest_path: Path,
    manifest: dict[str, Any],
    adoption: dict[str, Any],
    baseline: dict[str, Any] | None,
    evidence: dict[str, Any],
) -> list[Path]:
    expected = render_adoption_documents(manifest, adoption, baseline, evidence)
    root = manifest_path.parent
    written: list[Path] = []
    for relative, content in expected.items():
        destination = root / relative
        if destination.exists():
            current = destination.read_text(encoding="utf-8", errors="replace")
            generated = current.startswith(GENERATED_MARKER) or (
                destination.suffix == ".json"
                and JSON_GENERATED_MARKER in current[:200]
            )
            if not generated:
                raise FileExistsError(
                    f"refusing to overwrite non-generated document: {destination}"
                )
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8", newline="\n")
        written.append(destination)
    return written
