#!/usr/bin/env python3
"""Render deterministic Markdown and Mermaid architecture description views."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

from check_architecture import analyze_realtime_profile


GENERATED_MARKER = "<!-- GENERATED BY govern-modular-event-architecture; DO NOT EDIT -->"
EXTERNALLY_GENERATED_DOCUMENTS = {
    Path("generated/adoption-readiness.md"),
}
SUPPORTED_SCHEMA_VERSIONS = {"2.1.0", "2.2.0"}


LABELS = {
    "zh": {
        "architecture": "架構導覽",
        "system": "系統總覽",
        "parents": "Parent Views",
        "flows": "端到端 Flows",
        "modules": "模組",
        "purpose": "目的",
        "parent": "父模組",
        "status": "實作狀態",
        "inputs": "輸入 Ports",
        "outputs": "輸出 Ports",
        "events": "輸出 Events",
        "state": "擁有狀態",
        "effects": "副作用",
        "errors": "異常",
        "invariants": "不變條件",
        "entrypoints": "程式入口",
        "contracts": "公開 Symbols",
        "ports": "Port 契約",
        "event_contracts": "Event 契約",
        "structure": "結構圖",
        "flow_diagram": "Flow 圖",
        "steps": "執行步驟",
        "success": "成功結果",
        "none": "無",
        "system_purpose": "系統目的與程式入口",
        "main_function_tree": "主要功能樹",
        "function_guide": "功能導覽",
        "children": "子功能",
        "related_flows": "相關 Flows",
        "protection_rationale": "保護理由",
        "complete_reference": "完整技術參考",
    },
    "en": {
        "architecture": "Architecture Guide",
        "system": "System Overview",
        "parents": "Parent Views",
        "flows": "End-to-End Flows",
        "modules": "Modules",
        "purpose": "Purpose",
        "parent": "Parent",
        "status": "Implementation Status",
        "inputs": "Input Ports",
        "outputs": "Output Ports",
        "events": "Emitted Events",
        "state": "Owned State",
        "effects": "Side Effects",
        "errors": "Errors",
        "invariants": "Invariants",
        "entrypoints": "Entrypoints",
        "contracts": "Public Symbols",
        "ports": "Port Contracts",
        "event_contracts": "Event Contracts",
        "structure": "Structure",
        "flow_diagram": "Flow Diagram",
        "steps": "Ordered Steps",
        "success": "Success",
        "none": "None",
        "system_purpose": "System Purpose and Entrypoints",
        "main_function_tree": "Main Function Tree",
        "function_guide": "Function Guide",
        "children": "Children",
        "related_flows": "Related Flows",
        "protection_rationale": "Protection Rationale",
        "complete_reference": "Complete Technical Reference",
    },
}


def load_manifest(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError("manifest root must be a mapping")
    if data.get("schema_version") not in SUPPORTED_SCHEMA_VERSIONS:
        raise ValueError(
            "description views require schema_version 2.1.0 or 2.2.0"
        )
    return data


def _labels(manifest: dict[str, Any]) -> dict[str, str]:
    language = str(manifest.get("project", {}).get("documentation_language", "zh-TW")).lower()
    return LABELS["zh" if language.startswith("zh") else "en"]


def _escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _mermaid_label(value: Any) -> str:
    return str(value).replace('"', "'").replace("\n", " ")


def _node_id(value: str) -> str:
    return "n_" + re.sub(r"[^A-Za-z0-9_]", "_", value)


def _file_name(module_id: str) -> str:
    return module_id + ".md"


def _time_text(value: Any) -> str:
    if not isinstance(value, int) or isinstance(value, bool):
        return _escape(value)
    if value >= 1_000_000_000 and value % 1_000_000_000 == 0:
        return f"{value / 1_000_000_000:g} s ({value} ns)"
    if value >= 1_000_000 and value % 1_000_000 == 0:
        return f"{value / 1_000_000:g} ms ({value} ns)"
    if value >= 1_000 and value % 1_000 == 0:
        return f"{value / 1_000:g} us ({value} ns)"
    return f"{value} ns"


def _frequency_text(period_ns: Any) -> str:
    if not isinstance(period_ns, int) or isinstance(period_ns, bool) or period_ns <= 0:
        return "n/a"
    return f"{1_000_000_000 / period_ns:g} Hz"


def _list_text(values: list[Any], none_label: str) -> str:
    return ", ".join(f"`{_escape(item)}`" for item in values) if values else none_label


def _module_table(modules: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = [
        f"| ID | Level | Role | {labels['parent']} | {labels['status']} | {labels['purpose']} |",
        "|---|---|---|---|---|---|",
    ]
    for module in modules:
        purpose = module.get("description", {}).get("purpose", "")
        lines.append(
            f"| `{module.get('id')}` | {module.get('level')} | {module.get('role')} | "
            f"`{module.get('parent') or '-'}` | {module.get('implementation_status')} | {_escape(purpose)} |"
        )
    return lines


def _diagram_summary(
    manifest: dict[str, Any] | None, module: dict[str, Any]
) -> str:
    if not manifest or manifest.get("schema_version") != "2.2.0":
        return ""
    language = manifest.get("project", {}).get("diagram_language")
    summaries = module.get("description", {}).get("diagram_summaries", {})
    if not language or not isinstance(summaries, dict):
        return ""
    return str(summaries.get(str(language), ""))


def _module_diagram_label(
    manifest: dict[str, Any] | None,
    module: dict[str, Any],
    *,
    include_level: bool,
) -> str:
    module_id = str(module.get("id"))
    label = (
        f"{module_id} ({module.get('level')})"
        if include_level
        else module_id
    )
    summary = _diagram_summary(manifest, module)
    return f"{label}<br/>{summary}" if summary else label


def _structure_diagram(
    modules: list[dict[str, Any]],
    manifest: dict[str, Any] | None = None,
    include_dependencies: bool = True,
) -> list[str]:
    lines = ["```mermaid", "flowchart TD"]
    known = {str(module.get("id")) for module in modules}
    for module in modules:
        module_id = str(module.get("id"))
        label = _module_diagram_label(manifest, module, include_level=True)
        lines.append(f'    {_node_id(module_id)}["{_mermaid_label(label)}"]')
    for module in modules:
        module_id = str(module.get("id"))
        parent = module.get("parent")
        if parent in known:
            lines.append(f"    {_node_id(str(parent))} -->|owns| {_node_id(module_id)}")
        if include_dependencies:
            for target in module.get("depends_on", []):
                if target in known:
                    lines.append(f"    {_node_id(module_id)} -.->|depends| {_node_id(str(target))}")
    lines.append("```")
    return lines


def _function_guide(
    manifest: dict[str, Any], labels: dict[str, str]
) -> list[str]:
    modules = [
        item
        for item in manifest.get("modules", [])
        if isinstance(item, dict) and item.get("level") in {"L0", "L1", "L2"}
    ]
    flows = [
        item for item in manifest.get("flows", []) if isinstance(item, dict)
    ]
    lines: list[str] = []
    for module in modules:
        module_id = str(module.get("id"))
        description = module.get("description", {})
        children = [
            str(item.get("id"))
            for item in modules
            if item.get("parent") == module_id
        ]
        related = [
            flow
            for flow in flows
            if flow.get("owner") == module_id
            or any(
                step.get("module") == module_id
                for step in flow.get("steps", [])
                if isinstance(step, dict)
            )
        ]
        flow_links = [
            (
                f"[`{flow.get('id')}`]"
                f"(generated/{_file_name(str(flow.get('owner')))}"
                f"#{str(flow.get('id')).replace('.', '')})"
            )
            for flow in related
        ]
        lines.extend(
            [
                f"### `{module_id}`",
                "",
                f"- **{labels['purpose']}:** "
                f"{_escape(description.get('purpose', ''))}",
                f"- **{labels['children']}:** "
                f"{_list_text(children, labels['none'])}",
                f"- **{labels['related_flows']}:** "
                f"{', '.join(flow_links) if flow_links else labels['none']}",
            ]
        )
        rationale = [
            _escape(value) for value in description.get("invariants", [])
        ]
        rationale.extend(
            (
                f"{_escape(error.get('condition', ''))} → "
                f"{_escape(error.get('handling', ''))}"
            )
            for error in description.get("errors", [])
            if isinstance(error, dict)
        )
        lines.extend(
            [
                f"- **{labels['protection_rationale']}:** "
                f"{'; '.join(rationale) if rationale else labels['none']}",
                "",
            ]
        )
    return lines


def _code_links(entries: list[dict[str, Any]], prefix: str, none_label: str) -> str:
    if not entries:
        return none_label
    values = []
    for entry in entries:
        path = str(entry.get("path", ""))
        symbol = str(entry.get("symbol", ""))
        kind = str(entry.get("kind", ""))
        values.append(f"[`{symbol}`]({prefix}{path}) ({kind})")
    return "<br>".join(values)


def _module_card(module: dict[str, Any], labels: dict[str, str], prefix: str) -> list[str]:
    description = module.get("description", {})
    none = labels["none"]
    lines = [f"### `{module.get('id')}`", ""]
    lines.extend(
        [
            f"- **{labels['purpose']}:** {_escape(description.get('purpose', ''))}",
            f"- **{labels['parent']}:** `{module.get('parent') or '-'}`",
            f"- **{labels['status']}:** `{module.get('implementation_status')}`",
            f"- **{labels['inputs']}:** {_list_text(description.get('input_ports', []), none)}",
            f"- **{labels['outputs']}:** {_list_text(description.get('output_ports', []), none)}",
            f"- **{labels['events']}:** {_list_text(description.get('emitted_events', []), none)}",
        ]
    )
    states = description.get("owned_state", [])
    lines.append(
        f"- **{labels['state']}:** "
        + ("; ".join(f"`{_escape(item.get('name'))}` — {_escape(item.get('description'))}" for item in states) if states else none)
    )
    effects = description.get("side_effects", [])
    lines.append(
        f"- **{labels['effects']}:** "
        + ("; ".join(f"{_escape(item.get('description'))} (`{_escape(item.get('via_port', '-'))}`)" for item in effects) if effects else none)
    )
    errors = description.get("errors", [])
    lines.append(
        f"- **{labels['errors']}:** "
        + ("; ".join(f"`{_escape(item.get('id'))}`: {_escape(item.get('condition'))} → `{_escape(item.get('event'))}` → {_escape(item.get('handling'))}" for item in errors) if errors else none)
    )
    lines.append(f"- **{labels['invariants']}:** " + ("; ".join(_escape(item) for item in description.get("invariants", [])) or none))
    lines.append(f"- **{labels['entrypoints']}:** {_code_links(module.get('entrypoints', []), prefix, none)}")
    lines.append(f"- **{labels['contracts']}:** {_code_links(module.get('public_symbols', []), prefix, none)}")
    lines.append("")
    return lines


def _port_table(ports: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = ["| ID | Owner | Direction | Kind | Timing | Description | Symbols |", "|---|---|---|---|---|---|---|"]
    for port in ports:
        description = port.get("description", {})
        lines.append(
            f"| `{port.get('id')}` | `{port.get('owner')}` | {port.get('direction')} | {port.get('kind')} | "
            f"{description.get('timing')} | {_escape(description.get('purpose', ''))}: {_escape(description.get('data', ''))} | "
            f"{_list_text(port.get('symbols', []), labels['none'])} |"
        )
    return lines


def _event_table(events: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = ["| ID | Owner | Delivery | Emitted when | Purpose | Consumers |", "|---|---|---|---|---|---|"]
    for event in events:
        description = event.get("description", {})
        lines.append(
            f"| `{event.get('id')}` | `{event.get('owner')}` | {event.get('delivery')} | "
            f"{_escape(description.get('emitted_when', ''))} | {_escape(description.get('purpose', ''))} | "
            f"{_list_text(description.get('intended_consumers', []), labels['none'])} |"
        )
    return lines


def _type_table(types: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = [
        "| ID | Owner | Declaration | Visibility | Semantic kind | Consumers | References |",
        "|---|---|---|---|---|---|---|",
    ]
    for item in types:
        declaration = item.get("declaration", {})
        declared = (
            f"`{declaration.get('symbol')}` "
            f"({declaration.get('kind')}, `{declaration.get('path')}`)"
        )
        lines.append(
            f"| `{item.get('id')}` | `{item.get('owner')}` | {declared} | "
            f"{item.get('visibility')} | {item.get('semantic_kind')} | "
            f"{_list_text(item.get('consumers', []), labels['none'])} | "
            f"{_list_text(item.get('references', []), labels['none'])} |"
        )
    return lines


def _state_table(states: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = [
        "| ID | Owner | Declaration | Type | Visibility | Mutability | Read authority | Write authority |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for item in states:
        declaration = item.get("declaration", {})
        declared = (
            f"`{declaration.get('symbol')}` "
            f"({declaration.get('storage')}, `{declaration.get('path')}`)"
        )
        lines.append(
            f"| `{item.get('id')}` | `{item.get('owner')}` | {declared} | "
            f"`{item.get('type')}` | {item.get('visibility')} | {item.get('mutability')} | "
            f"{_list_text(item.get('read_authority', []), labels['none'])} | "
            f"{_list_text(item.get('write_authority', []), labels['none'])} |"
        )
    return lines


def _boundary_table(mappings: list[dict[str, Any]], labels: dict[str, str]) -> list[str]:
    lines = [
        "| Interaction | Producer | Consumer | Parent | Producer contract | Consumer contract | Mapping owner | State accessed | Allowed edges | Forbidden edges |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for item in mappings:
        lines.append(
            f"| `{item.get('id')}`: {_escape(item.get('interaction', ''))} | "
            f"`{item.get('producer')}` | `{item.get('consumer')}` | `{item.get('parent')}` | "
            f"`{item.get('producer_contract') or '-'}` | "
            f"`{item.get('consumer_contract') or '-'}` | "
            f"`{item.get('mapping_owner') or '-'}` | "
            f"{_list_text(item.get('state_objects', []), labels['none'])} | "
            f"{_list_text(item.get('allowed_edges', []), labels['none'])} | "
            f"{_list_text(item.get('forbidden_edges', []), labels['none'])} |"
        )
    return lines


def _flow_view(flow: dict[str, Any], labels: dict[str, str], manifest: dict[str, Any] | None = None) -> list[str]:
    lines = [f"### `{flow.get('id')}`", "", _escape(flow.get("description", "")), "", f"#### {labels['flow_diagram']}", "", "```mermaid", "sequenceDiagram"]
    modules = []
    owner = str(flow.get("owner"))
    for value in [owner] + [str(step.get("module")) for step in flow.get("steps", [])]:
        if value not in modules:
            modules.append(value)
    for module_id in modules:
        module = next(
            (
                item
                for item in (manifest or {}).get("modules", [])
                if isinstance(item, dict) and str(item.get("id")) == module_id
            ),
            {"id": module_id},
        )
        label = _module_diagram_label(
            manifest, module, include_level=False
        )
        lines.append(
            f"    participant {_node_id(module_id)} as {_mermaid_label(label)}"
        )
    previous = _node_id(owner)
    for step in flow.get("steps", []):
        current = _node_id(str(step.get("module")))
        arrow = "->>" if current == previous else "->>+"
        lines.append(f"    {previous}{arrow}{current}: {_mermaid_label(step.get('action', ''))}")
        emitted = step.get("emits", [])
        if emitted:
            lines.append(f"    Note right of {current}: {_mermaid_label(', '.join(str(item) for item in emitted))}")
        sync_query = next(
            (
                str(port.get("id"))
                for port in (manifest or {}).get("ports", [])
                if isinstance(port, dict)
                and str(port.get("id")) in step.get("receives", [])
                and port.get("kind") == "query"
                and port.get("description", {}).get("timing") == "sync"
            ),
            None,
        )
        if sync_query:
            lines.append(
                f"    {current}-->>-{previous}: {_mermaid_label(sync_query)} result"
            )
        elif current != previous:
            lines.append(f"    {current}-->>-{previous}: step {step.get('order')}")
            previous = current
    lines.append("```")
    lines.extend(["", f"#### {labels['steps']}", "", "| # | Module | Action | Receives | Emits | State changes | Side effects |", "|---|---|---|---|---|---|---|"])
    for step in flow.get("steps", []):
        lines.append(
            f"| {step.get('order')} | `{step.get('module')}` | {_escape(step.get('action', ''))} | "
            f"{_list_text(step.get('receives', []), labels['none'])} | {_list_text(step.get('emits', []), labels['none'])} | "
            f"{_escape('; '.join(str(item) for item in step.get('state_changes', [])) or labels['none'])} | "
            f"{_escape('; '.join(str(item) for item in step.get('side_effects', [])) or labels['none'])} |"
        )
    lines.extend(["", f"- **{labels['success']}:** {_escape(flow.get('success', {}).get('result', ''))}"])
    for error in flow.get("errors", []):
        error_ref = error.get("event") or error.get("code")
        lines.append(f"- **{labels['errors']}:** {_escape(error.get('condition'))} → `{_escape(error_ref)}` → {_escape(error.get('handling'))}")
    if manifest and manifest.get("schema_version") in SUPPORTED_SCHEMA_VERSIONS:
        workloads = [item for item in manifest.get("workloads", []) if item.get("flow") == flow.get("id")]
        if workloads:
            lines.extend(["", "#### Execution efficiency", ""])
            for workload in workloads:
                workload_id = str(workload.get("id"))
                profile_ids = sorted(
                    {
                        str(item.get("profile"))
                        for item in manifest.get("execution_mappings", [])
                        if item.get("workload") == workload_id
                    }
                )
                profile_links = [f"[`{profile_id}`](execution-{_file_name(profile_id)})" for profile_id in profile_ids]
                lines.append(
                    f"- Workload `{workload_id}`: `{workload.get('timing_class')}`; "
                    f"steps {_list_text(workload.get('steps', []), labels['none'])}; "
                    f"profiles {', '.join(profile_links) if profile_links else labels['none']}."
                )
    lines.append("")
    return lines


def _execution_view(manifest: dict[str, Any], profile: dict[str, Any]) -> list[str]:
    profile_id = str(profile.get("id"))
    units = [item for item in manifest.get("execution_units", []) if item.get("profile") == profile_id]
    mappings = [item for item in manifest.get("execution_mappings", []) if item.get("profile") == profile_id]
    channels = [item for item in manifest.get("execution_channels", []) if item.get("profile") == profile_id]
    data_profiles = [item for item in manifest.get("data_access_profiles", []) if item.get("profile") == profile_id]
    micro_profiles = [item for item in manifest.get("microarchitecture_profiles", []) if item.get("profile") == profile_id]
    target = profile.get("target", {})
    lines = [
        GENERATED_MARKER,
        "",
        f"# Execution profile `{profile_id}`",
        "",
        f"- **Status:** `{profile.get('status')}`",
        f"- **Platform:** `{_escape(target.get('platform', 'unconfirmed'))}`",
        f"- **CPU:** `{_escape(target.get('cpu', 'unconfirmed'))}`",
        f"- **Runtime:** `{_escape(target.get('runtime', 'unconfirmed'))}`",
        f"- **Compiler:** `{_escape(target.get('compiler', 'unconfirmed'))}`",
    ]
    studies = [
        item
        for item in manifest.get("realtime_scheduling_studies", [])
        if profile_id in item.get("candidate_profiles", [])
    ]
    for study in studies:
        study_id = str(study.get("id"))
        lines.append(
            f"- **Real-time scheduling study:** "
            f"[`{study_id}`](realtime-study-{_file_name(study_id)})"
        )
    lines.extend([
        "",
        "## Execution Units",
        "",
        "| ID | Kind | Priority | Affinity | Concurrency | Resources |",
        "|---|---|---|---|---|---|",
    ])
    for unit in units:
        lines.append(
            f"| `{unit.get('id')}` | {unit.get('kind')} | {_escape(unit.get('priority'))} | "
            f"{_escape(unit.get('affinity'))} | {unit.get('concurrency')} | {_escape(unit.get('resources'))} |"
        )
    lines.extend(["", "## Workload mappings", "", "| ID | Workload | Steps | Units | Serialization | Reentrant | WCET |", "|---|---|---|---|---|---|---|"])
    for mapping in mappings:
        lines.append(
            f"| `{mapping.get('id')}` | `{mapping.get('workload')}` | {_list_text(mapping.get('steps', []), 'None')} | "
            f"{_list_text(mapping.get('units', []), 'None')} | {_escape(mapping.get('serialization'))} | "
            f"{_escape(mapping.get('reentrant'))} | {_escape(mapping.get('wcet'))} |"
        )
    lines.extend(["", "## Execution Channels", "", "| ID | From | To | Contracts | Capacity | Ordering | Copy | Timeout | Overload |", "|---|---|---|---|---|---|---|---|---|"])
    for channel in channels:
        lines.append(
            f"| `{channel.get('id')}` | `{channel.get('from_unit')}` | `{channel.get('to_unit')}` | "
            f"{_list_text(channel.get('contract_refs', []), 'None')} | {channel.get('capacity')} | "
            f"{_escape(channel.get('ordering'))} | {_escape(channel.get('copy_policy'))} | "
            f"{_escape(channel.get('timeout_ms'))} | `{channel.get('overload')}` |"
        )
    lines.extend(["", "## Data Access Profiles", "", "| ID | Workload | Tier | Layout | Working set | Stride | Alignment | Cache target |", "|---|---|---|---|---|---|---|---|"])
    for item in data_profiles:
        lines.append(
            f"| `{item.get('id')}` | `{item.get('workload')}` | `{item.get('tier')}` | {_escape(item.get('layout'))} | "
            f"{_escape(item.get('active_working_set_bytes'))} | {_escape(item.get('stride_bytes'))} | "
            f"{_escape(item.get('alignment_bytes'))} | {_escape(item.get('cache_target'))} |"
        )
    lines.extend(["", "## Microarchitecture Profiles", "", "| ID | Workload | Tier | SIMD | Compiler | PGO | LTO | Benchmark |", "|---|---|---|---|---|---|---|---|"])
    for item in micro_profiles:
        lines.append(
            f"| `{item.get('id')}` | `{item.get('workload')}` | `{item.get('tier')}` | "
            f"{_escape(item.get('simd_eligibility'))} | {_escape(item.get('compiler'))} | "
            f"{_escape(item.get('pgo'))} | {_escape(item.get('lto'))} | {_escape(item.get('benchmark', 'None'))} |"
        )
    lines.append("")
    return lines


def _realtime_study_view(manifest: dict[str, Any], study: dict[str, Any]) -> list[str]:
    study_id = str(study.get("id"))
    selected = str(study.get("selected_profile"))
    profiles = {
        str(item.get("id")): item
        for item in manifest.get("execution_profiles", [])
        if isinstance(item, dict)
    }
    units = {
        str(item.get("id")): item
        for item in manifest.get("execution_units", [])
        if isinstance(item, dict)
    }
    mappings = {
        str(item.get("id")): item
        for item in manifest.get("execution_mappings", [])
        if isinstance(item, dict)
    }
    workloads = {
        str(item.get("id")): item
        for item in manifest.get("workloads", [])
        if isinstance(item, dict)
    }
    channels = {
        str(item.get("id")): item
        for item in manifest.get("execution_channels", [])
        if isinstance(item, dict)
    }
    flow_chains = [
        item for item in study.get("flow_chains", []) if isinstance(item, dict)
    ]
    results = {
        profile_id: analyze_realtime_profile(
            profiles[profile_id],
            units,
            mappings,
            channels,
            workloads,
            flow_chains,
            analysis_method=str(study.get("analysis_method")),
        )
        for profile_id in study.get("candidate_profiles", [])
        if profile_id in profiles
    }
    approval = study.get("selection_approval", {})
    final_approval = study.get("final_approval", {})
    labels = _labels(manifest)
    is_zh = labels is LABELS["zh"]
    def local(zh: str, en: str) -> str:
        return zh if is_zh else en

    heading = "即時排程設計研究" if is_zh else "Real-time Scheduling Study"
    lines = [
        GENERATED_MARKER,
        "",
        f"# {heading} `{study_id}`",
        "",
        f"- **{'狀態' if is_zh else 'Phase'}:** `{study.get('analysis_phase')}`",
        f"- **{'分析方法' if is_zh else 'Analysis method'}:** "
        f"`{study.get('analysis_method')}`",
        f"- **{'選定方案' if is_zh else 'Selected profile'}:** "
        f"[`{selected}`](execution-{_file_name(selected)})",
        f"- **{'目標' if is_zh else 'Objective'}:** {_escape(study.get('objective'))}",
        f"- **{'涵蓋 Flows' if is_zh else 'Flows'}:** "
        f"{_list_text(study.get('flow_refs', []), labels['none'])}",
        f"- **{'涵蓋 Workloads' if is_zh else 'Workloads'}:** "
        f"{_list_text(study.get('workload_refs', []), labels['none'])}",
        "",
        f"## {'需求與假設' if is_zh else 'Requirements and assumptions'}",
        "",
    ]
    for requirement in study.get("requirements", []):
        lines.append(f"- **{'需求' if is_zh else 'Requirement'}:** {_escape(requirement)}")
    for assumption in study.get("assumptions", []):
        lines.append(f"- **{'假設' if is_zh else 'Assumption'}:** {_escape(assumption)}")

    lines.extend(
        [
            "",
            f"## {'候選方案比較' if is_zh else 'Candidate comparison'}",
            "",
            f"| {local('方案', 'Profile')} | {local('執行模型', 'Execution model')} | "
            f"{local('已選定', 'Selected')} | {local('結果', 'Outcome')} | "
            f"{local('任務數', 'Tasks')} | {local('核心數', 'Cores')} | "
            f"{local('最高使用率', 'Max utilization')} | "
            f"{local('Gate 判定', 'Gate verdict')} | "
            f"{local('Soft 風險數', 'Soft risks')} |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for profile_id in study.get("candidate_profiles", []):
        result = results.get(profile_id, {})
        profile = profiles.get(profile_id, {})
        scheduler = profile.get("scheduler", {})
        task_count = len(result.get("tasks", {}))
        max_utilization = max(
            (
                float(item.get("utilization", 0))
                for item in result.get("cores", {}).values()
            ),
            default=0.0,
        )
        outcome = (
            "selected"
            if profile_id == selected
            else study.get("candidate_outcomes", {}).get(profile_id, "unrecorded")
        )
        lines.append(
            f"| [`{profile_id}`](execution-{_file_name(profile_id)}) | "
            f"`{profile.get('execution_model')}` | "
            f"{local('是', 'yes') if profile_id == selected else local('否', 'no')} | "
            f"`{outcome}` | "
            f"{task_count} | {scheduler.get('core_count', 'n/a')} | "
            f"{max_utilization:.6f} | `{result.get('verdict', 'BLOCKED')}` | "
            f"{len(result.get('soft_risks', []))} |"
        )
    lines.extend(
        [
            "",
            f"- **{'選擇理由' if is_zh else 'Selection rationale'}:** "
            f"{_escape(study.get('selection_rationale'))}",
            "",
            f"## {'候選方案細節' if is_zh else 'Candidate details'}",
            "",
        ]
    )

    for profile_id in study.get("candidate_profiles", []):
        profile = profiles.get(profile_id, {})
        result = results.get(profile_id, {})
        scheduler = profile.get("scheduler", {})
        overheads = profile.get("overheads", {})
        lines.extend(
            [
                f"### `{profile_id}`",
                "",
                f"- **{local('執行模型', 'Execution model')}:** "
                f"`{profile.get('execution_model')}`",
                f"- **{local('分析方法', 'Analysis method')}:** "
                f"`{result.get('analysis_method')}`",
                f"- **{local('排程器相容性', 'Scheduler compatibility')}:** "
                f"`{'PASS' if result.get('scheduler_compatible') else 'BLOCKED'}`",
                f"- **{local('排程器', 'Scheduler')}:** "
                f"`{scheduler.get('model')}` / "
                f"`{scheduler.get('priority_assignment')}` / "
                f"`{scheduler.get('preemption')}` / "
                f"{local('任務遷移', 'migration')} "
                f"`{scheduler.get('migration')}`",
                f"- **{local('資源存取協定', 'Resource protocol')}:** "
                f"`{scheduler.get('resource_access_protocol')}`",
                f"- **{local('計時器解析度', 'Timer resolution')}:** "
                f"{_time_text(scheduler.get('timer_resolution_ns'))}",
                f"- **{local('額外成本', 'Overheads')}:** "
                f"{local('情境切換', 'context switch')} "
                f"{_time_text(overheads.get('context_switch_ns'))}; "
                f"{local('派送', 'dispatch')} "
                f"{_time_text(overheads.get('dispatch_ns'))}; "
                f"{local('搶佔', 'preemption')} "
                f"{_time_text(overheads.get('preemption_ns'))}; "
                f"{local('計時器中斷', 'timer interrupt')} "
                f"{_time_text(overheads.get('timer_interrupt_ns'))}",
                "",
                f"#### {'每核心 RM 排序' if is_zh else 'Per-core RM ordering'}",
                "",
                f"| {local('核心', 'Core')} | {local('RM 順序', 'RM order')} | "
                f"{local('使用率', 'Utilization')} | "
                f"{local('Liu-Layland 充分界限', 'Liu-Layland sufficient bound')} | "
                f"{local('界限篩選', 'Bound screen')} |",
                "|---|---|---|---|---|",
            ]
        )
        for core, core_result in sorted(result.get("cores", {}).items()):
            lines.append(
                f"| `{core}` | {_list_text(core_result.get('rm_order', []), 'None')} | "
                f"{core_result.get('utilization', 0):.6f} | "
                f"{core_result.get('liu_layland_bound', 0):.6f} | "
                f"`{'PASS' if core_result.get('sufficient_bound_pass') else 'INCONCLUSIVE'}` |"
            )
        lines.extend(
            [
                "",
                f"#### {'ISR 干擾模型' if is_zh else 'ISR interference model'}",
                "",
                f"| ISR | {local('核心', 'Core')} | WCET | "
                f"{local('最小到達間隔', 'Minimum inter-arrival')} | "
                f"{local('抖動', 'Jitter')} |",
                "|---|---|---|---|---|",
            ]
        )
        for isr_id, isr in sorted(result.get("interrupts", {}).items()):
            lines.append(
                f"| `{isr_id}` | {isr.get('core')} | "
                f"{_time_text(isr.get('execution_ns'))} | "
                f"{_time_text(isr.get('period_ns'))} | "
                f"{_time_text(isr.get('jitter_ns'))} |"
            )
        lines.extend(
            [
                "",
                f"#### {'Task RTA' if is_zh else 'Task RTA'}",
                "",
                f"| Task | {local('時序分類', 'Timing class')} | "
                f"{local('核心', 'Core')} | {local('優先權', 'Priority')} | "
                f"{local('啟動方式', 'Activation')} | {local('頻率', 'Frequency')} | "
                f"{local('執行時間', 'Execution')} | {local('阻塞', 'Blocking')} | "
                f"{local('抖動', 'Jitter')} | {local('反應時間', 'Response')} | "
                f"{local('截止期限', 'Deadline')} | RTA {local('判定', 'verdict')} |",
                "|---|---|---|---|---|---|---|---|---|---|---|---|",
            ]
        )
        for task_id, task_result in sorted(
            result.get("tasks", {}).items(),
            key=lambda item: (item[1].get("core"), item[1].get("period_ns"), item[0]),
        ):
            unit = units.get(task_id, {})
            activation = unit.get("realtime_task", {}).get("activation", {})
            lines.append(
                f"| `{task_id}` | `{task_result.get('timing_class')}` | "
                f"{task_result.get('core')} | "
                f"{task_result.get('priority')} | `{activation.get('kind')}` | "
                f"{_frequency_text(task_result.get('period_ns'))} | "
                f"{_time_text(task_result.get('execution_ns'))} | "
                f"{_time_text(task_result.get('blocking_ns'))} | "
                f"{_time_text(task_result.get('jitter_ns'))} | "
                f"{_time_text(task_result.get('response_ns'))} | "
                f"{_time_text(task_result.get('deadline_ns'))} | "
                f"`{task_result.get('rta_verdict')}` |"
            )
        lines.extend(
            [
                "",
                f"#### {'WCET 上界證據' if is_zh else 'WCET bound evidence'}",
                "",
                f"| Task | Mapping | {local('設計預算', 'Design budget')} | "
                f"{local('最終上界', 'Final bound')} | {local('依據', 'Basis')} | "
                f"{local('證據路徑', 'Evidence path')} | SHA-256 |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for task_id, unit in sorted(units.items()):
            if unit.get("profile") != profile_id or unit.get("kind") != "dedicated-task":
                continue
            for component in unit.get("realtime_task", {}).get("demand_components", []):
                if not isinstance(component, dict):
                    continue
                lines.append(
                    f"| `{task_id}` | `{component.get('mapping')}` | "
                    f"{_time_text(component.get('budget_ns'))} | "
                    f"{_time_text(component.get('final_ns'))} | "
                    f"`{component.get('basis', 'design-budget')}` | "
                    f"`{component.get('evidence_path', 'pending')}` | "
                    f"`{component.get('evidence_sha256', 'pending')}` |"
                )
        profile_channels = [
            item
            for item in channels.values()
            if item.get("profile") == profile_id
        ]
        lines.extend(
            [
                "",
                f"#### {'Queue／Notification 與跨核心成本' if is_zh else 'Queue, notification, and cross-core cost'}",
                "",
                f"| Channel | {local('來源', 'From')} | {local('目的地', 'To')} | "
                f"{local('跨核心', 'Cross-core')} | "
                f"{local('通知延遲', 'Notification')} | "
                f"{local('釋放抖動', 'Release jitter')} | "
                f"{local('複製成本', 'Copy cost')} | "
                f"{local('CPU 成本歸屬', 'CPU accounting')} |",
                "|---|---|---|---|---|---|---|---|",
            ]
        )
        for channel in profile_channels:
            timing = channel.get("realtime_timing", {})
            accounting = "; ".join(
                f"{item.get('unit')}={_time_text(item.get('cost_ns'))}"
                for item in timing.get("cpu_cost_accounting", [])
                if isinstance(item, dict)
            )
            lines.append(
                f"| `{channel.get('id')}` | `{channel.get('from_unit')}` | "
                f"`{channel.get('to_unit')}` | "
                f"`{timing.get('cross_core')}` | "
                f"{_time_text(timing.get('notification_latency_ns'))} | "
                f"{_time_text(timing.get('release_jitter_ns'))} | "
                f"{_time_text(timing.get('copy_cost_ns'))} | "
                f"{_escape(accounting or 'None')} |"
            )
        lines.extend(
            [
                "",
                f"#### {'端到端 Flow' if is_zh else 'End-to-end Flow'}",
                "",
                f"| Chain | Flow | {local('時序分類', 'Timing class')} | "
                f"{local('依序 Tasks', 'Ordered tasks')} | "
                f"{local('依序 Channels', 'Ordered channels')} | "
                f"{local('反應上界', 'Response bound')} | "
                f"{local('截止期限', 'Deadline')} | RTA {local('判定', 'verdict')} |",
                "|---|---|---|---|---|---|---|---|",
            ]
        )
        profile_chains = {
            str(item.get("id")): item
            for item in flow_chains
            if item.get("profile") == profile_id
        }
        for chain_id, flow_result in result.get("flows", {}).items():
            chain = profile_chains.get(chain_id, {})
            lines.append(
                f"| `{chain_id}` | `{flow_result.get('flow')}` | "
                f"`{flow_result.get('timing_class')}` | "
                f"{_list_text(chain.get('ordered_units', []), 'None')} | "
                f"{_list_text(chain.get('ordered_channels', []), 'None')} | "
                f"{_time_text(flow_result.get('response_ns'))} | "
                f"{_time_text(flow_result.get('deadline_ns'))} | "
                f"`{flow_result.get('rta_verdict')}` |"
            )
        if result.get("soft_risks"):
            lines.extend(
                [
                    "",
                    f"#### {'Soft real-time 風險' if is_zh else 'Soft real-time risks'}",
                    "",
                ]
            )
            for risk in result.get("soft_risks", []):
                lines.append(f"- `SOFT_RISK`: {_escape(risk)}")
        if profile_id != selected:
            reason = study.get("rejection_reasons", {}).get(profile_id)
            if reason:
                lines.extend(
                    [
                        "",
                        f"- **{'拒絕理由' if is_zh else 'Rejection reason'}:** "
                        f"{_escape(reason)}",
                    ]
                )
        lines.append("")

    lines.extend(
        [
            f"## {'核准與證據狀態' if is_zh else 'Approval and evidence status'}",
            "",
            f"- **{local('方案核准人', 'Selection approved by')}:** "
            f"`{approval.get('approved_by', 'missing')}`",
            f"- **{local('方案核准日期', 'Selection approval date')}:** "
            f"`{approval.get('approval_date', 'missing')}`",
            f"- **{local('方案核准參考', 'Selection reference')}:** "
            f"`{approval.get('approval_reference', 'missing')}`",
            f"- **{local('最終核准人', 'Final approved by')}:** "
            f"`{final_approval.get('approved_by', 'pending')}`",
            f"- **{local('最終核准日期', 'Final approval date')}:** "
            f"`{final_approval.get('approval_date', 'pending')}`",
            f"- **{local('最終核准參考', 'Final reference')}:** "
            f"`{final_approval.get('approval_reference', 'pending')}`",
            "",
            f"### {'Soft SLO 驗證計畫' if is_zh else 'Soft SLO validation plans'}",
            "",
            f"| Workload | {local('驗證計畫', 'Validation plan')} | "
            f"{local('證據格式', 'Evidence format')} | "
            f"{local('風險核准人', 'Risk approver')} | "
            f"{local('核准參考', 'Approval reference')} |",
            "|---|---|---|---|---|",
        ]
    )
    soft_plans = study.get("soft_acceptance_plans", [])
    if soft_plans:
        for plan in soft_plans:
            if not isinstance(plan, dict):
                continue
            risk_approval = plan.get("risk_approval", {})
            lines.append(
                f"| `{plan.get('workload')}` | "
                f"`{plan.get('validation_plan_path')}` | "
                f"`{plan.get('evidence_format')}` | "
                f"`{risk_approval.get('approved_by')}` | "
                f"`{risk_approval.get('approval_reference')}` |"
            )
    else:
        lines.append("| `not-applicable` | `-` | `-` | `-` | `-` |")
    lines.extend(
        [
            "",
            f"### {'Soft SLO 最終結果' if is_zh else 'Final soft SLO results'}",
            "",
            f"| Workload | {local('判定', 'Verdict')} | "
            f"{local('證據路徑', 'Evidence path')} | SHA-256 | "
            f"{local('方案', 'Profile')} | Manifest SHA-256 |",
            "|---|---|---|---|---|---|",
        ]
    )
    soft_results = study.get("soft_slo_results", [])
    if soft_results:
        for slo in soft_results:
            if not isinstance(slo, dict):
                continue
            lines.append(
                f"| `{slo.get('workload')}` | `{slo.get('verdict')}` | "
                f"`{slo.get('evidence_path')}` | `{slo.get('evidence_sha256')}` | "
                f"`{slo.get('profile_id')}` | `{slo.get('manifest_sha256')}` |"
            )
    else:
        lines.append("| `pending` | `pending` | `pending` | `pending` | `pending` | `pending` |")
    lines.extend(
        [
            "",
            f"### {'Runtime 證據綁定' if is_zh else 'Runtime evidence bindings'}",
            "",
            f"| {local('路徑', 'Path')} | SHA-256 | "
            f"{local('方案', 'Profile')} | Manifest SHA-256 |",
            "|---|---|---|---|",
        ]
    )
    selected_profile = profiles.get(selected, {})
    runtime_evidence = selected_profile.get("runtime_evidence", [])
    if runtime_evidence:
        for evidence in runtime_evidence:
            if not isinstance(evidence, dict):
                continue
            lines.append(
                f"| `{evidence.get('path')}` | `{evidence.get('sha256')}` | "
                f"`{evidence.get('profile_id')}` | `{evidence.get('manifest_sha256')}` |"
            )
    else:
        lines.append("| `pending` | `pending` | `pending` | `pending` |")
    lines.extend(
        [
            "",
            (
                "Manifest 與上界證據是正式輸入；本產生的 Markdown "
                "僅供唯讀審查。"
                if is_zh
                else "The manifest and bound evidence are authoritative inputs. "
                "This generated Markdown is a read-only review projection."
            ),
            "",
        ]
    )
    return lines


def render_documents(manifest: dict[str, Any]) -> dict[Path, str]:
    labels = _labels(manifest)
    project = manifest.get("project", {})
    modules = [item for item in manifest.get("modules", []) if isinstance(item, dict)]
    ports = [item for item in manifest.get("ports", []) if isinstance(item, dict)]
    events = [item for item in manifest.get("events", []) if isinstance(item, dict)]
    types = [item for item in manifest.get("types", []) if isinstance(item, dict)]
    state_objects = [
        item for item in manifest.get("state_objects", []) if isinstance(item, dict)
    ]
    boundary_mappings = [
        item for item in manifest.get("boundary_mappings", []) if isinstance(item, dict)
    ]
    flows = [item for item in manifest.get("flows", []) if isinstance(item, dict)]
    parents = [module for module in modules if module.get("level") in {"L0", "L1"}]

    index = [GENERATED_MARKER, "", f"# {project.get('name')} {labels['architecture']}", "", f"- Standard: `{manifest.get('standard_version')}`", f"- Schema: `{manifest.get('schema_version')}`"]
    if manifest.get("schema_version") == "2.2.0":
        main_modules = [
            module
            for module in modules
            if module.get("level") in {"L0", "L1", "L2"}
        ]
        index.extend(["", f"## {labels['system_purpose']}", ""])
        for module in main_modules:
            if module.get("level") != "L0":
                continue
            index.extend(
                [
                    f"- `{module.get('id')}` — "
                    f"{_escape(module.get('description', {}).get('purpose', ''))}",
                    f"  - {labels['entrypoints']}: "
                    f"{_code_links(module.get('entrypoints', []), '../', labels['none'])}",
                ]
            )
        index.extend(["", f"## {labels['main_function_tree']}", ""])
        index.extend(
            _structure_diagram(
                main_modules, manifest, include_dependencies=False
            )
        )
        index.extend(["", f"## {labels['function_guide']}", ""])
        index.extend(_function_guide(manifest, labels))
    else:
        index.extend(["", f"## {labels['system']}", ""])
        index.extend(_structure_diagram(modules, manifest))
    index.extend(["", f"## {labels['parents']}", ""])
    for parent in parents:
        parent_id = str(parent.get("id"))
        index.append(f"- [`{parent_id}`](generated/{_file_name(parent_id)}) — {_escape(parent.get('description', {}).get('purpose', ''))}")
    index.extend(["", f"## {labels['flows']}", ""])
    for flow in flows:
        owner = str(flow.get("owner"))
        index.append(f"- [`{flow.get('id')}`](generated/{_file_name(owner)}#{str(flow.get('id')).replace('.', '')}) — {_escape(flow.get('description', ''))}")
    if manifest.get("schema_version") == "2.2.0":
        index.extend(
            [
                "",
                f"## {labels['complete_reference']}",
                "",
                f"## {labels['system']}",
                "",
            ]
        )
        index.extend(_structure_diagram(modules, manifest))
    index.extend(["", "## Type Catalog", ""])
    for item in types:
        index.append(
            f"- `{item.get('id')}` — `{item.get('owner')}` / "
            f"`{item.get('semantic_kind')}` / `{item.get('visibility')}`"
        )
    index.extend(["", "## State Ownership", ""])
    for item in state_objects:
        index.append(
            f"- `{item.get('id')}` / `{item.get('owner')}` / "
            f"`{item.get('mutability')}` / `{item.get('visibility')}`"
        )
    index.extend(["", "## Cross-module Mapping", ""])
    for item in boundary_mappings:
        index.append(
            f"- `{item.get('id')}` / `{item.get('parent')}` / "
            f"`{item.get('producer')}` to `{item.get('consumer')}`"
        )
    if manifest.get("schema_version") in SUPPORTED_SCHEMA_VERSIONS:
        index.extend(
            [
                "",
                "## Adoption Readiness",
                "",
                "- [Human-readable readiness](generated/adoption-readiness.md)",
                "- [Machine-readable readiness](generated/adoption-readiness.json)",
            ]
        )
        index.extend(["", "## Execution Profiles", ""])
        for profile in manifest.get("execution_profiles", []):
            profile_id = str(profile.get("id"))
            index.append(
                f"- [`{profile_id}`](generated/execution-{_file_name(profile_id)}) "
                f"— `{profile.get('status')}` / `{profile.get('target', {}).get('platform', 'unconfirmed')}`"
            )
        index.extend(["", "## Real-time Scheduling Studies", ""])
        for study in manifest.get("realtime_scheduling_studies", []):
            study_id = str(study.get("id"))
            index.append(
                f"- [`{study_id}`](generated/realtime-study-{_file_name(study_id)}) "
                f"— `{study.get('analysis_method')}` / "
                f"`{study.get('analysis_phase')}` / selected "
                f"`{study.get('selected_profile')}`"
            )
    index.append("")

    system = [GENERATED_MARKER, "", f"# {labels['system']}", ""]
    system.extend(_structure_diagram(modules, manifest))
    system.extend(["", f"## {labels['modules']}", ""])
    system.extend(_module_table(modules, labels))
    system.append("")
    for module in modules:
        system.extend(_module_card(module, labels, "../../"))
    system.extend([f"## {labels['ports']}", ""])
    system.extend(_port_table(ports, labels))
    system.extend(["", f"## {labels['event_contracts']}", ""])
    system.extend(_event_table(events, labels))
    system.extend(["", "## Type Catalog", ""])
    system.extend(_type_table(types, labels))
    system.extend(["", "## State Ownership", ""])
    system.extend(_state_table(state_objects, labels))
    system.extend(["", "## Cross-module Mapping", ""])
    system.extend(_boundary_table(boundary_mappings, labels))
    system.append("")

    documents: dict[Path, str] = {
        Path("ARCHITECTURE.md"): "\n".join(index),
        Path("generated/system.md"): "\n".join(system),
    }
    for parent in parents:
        parent_id = str(parent.get("id"))
        visible = [parent] + [module for module in modules if module.get("parent") == parent_id]
        visible_ids = {str(module.get("id")) for module in visible}
        page = [GENERATED_MARKER, "", f"# `{parent_id}`", "", f"## {labels['structure']}", ""]
        page.extend(_structure_diagram(visible, manifest))
        page.extend(["", f"## {labels['modules']}", ""])
        page.extend(_module_table(visible, labels))
        page.append("")
        for module in visible:
            page.extend(_module_card(module, labels, "../../"))
        selected_ports = [port for port in ports if str(port.get("owner")) in visible_ids]
        selected_events = [event for event in events if str(event.get("owner")) in visible_ids]
        selected_types = [item for item in types if str(item.get("owner")) in visible_ids]
        selected_states = [
            item for item in state_objects if str(item.get("owner")) in visible_ids
        ]
        selected_mappings = [
            item
            for item in boundary_mappings
            if str(item.get("parent")) == parent_id
        ]
        page.extend([f"## {labels['ports']}", ""])
        page.extend(_port_table(selected_ports, labels))
        page.extend(["", f"## {labels['event_contracts']}", ""])
        page.extend(_event_table(selected_events, labels))
        page.extend(["", "## Type Catalog", ""])
        page.extend(_type_table(selected_types, labels))
        page.extend(["", "## State Ownership", ""])
        page.extend(_state_table(selected_states, labels))
        page.extend(["", "## Cross-module Mapping", ""])
        page.extend(_boundary_table(selected_mappings, labels))
        page.extend(["", f"## {labels['flows']}", ""])
        for flow in flows:
            if flow.get("owner") == parent_id:
                page.extend(_flow_view(flow, labels, manifest))
        documents[Path("generated") / _file_name(parent_id)] = "\n".join(page)
    if manifest.get("schema_version") in SUPPORTED_SCHEMA_VERSIONS:
        for profile in manifest.get("execution_profiles", []):
            profile_id = str(profile.get("id"))
            documents[Path("generated") / f"execution-{_file_name(profile_id)}"] = "\n".join(
                _execution_view(manifest, profile)
            )
        for study in manifest.get("realtime_scheduling_studies", []):
            study_id = str(study.get("id"))
            documents[
                Path("generated") / f"realtime-study-{_file_name(study_id)}"
            ] = "\n".join(_realtime_study_view(manifest, study))
    return {path: text.rstrip() + "\n" for path, text in documents.items()}


def compare_documents(manifest: dict[str, Any], manifest_path: Path) -> list[tuple[str, str, str]]:
    architecture_root = manifest_path.parent
    expected = render_documents(manifest)
    diagnostics: list[tuple[str, str, str]] = []
    for relative, content in expected.items():
        destination = architecture_root / relative
        if not destination.is_file():
            diagnostics.append(("DOC001", relative.as_posix(), "generated architecture document is missing"))
        elif destination.read_text(encoding="utf-8") != content:
            diagnostics.append(("DOC002", relative.as_posix(), "generated architecture document is stale"))
    generated_root = architecture_root / "generated"
    if generated_root.is_dir():
        for path in generated_root.rglob("*.md"):
            relative = path.relative_to(architecture_root)
            if relative not in expected and relative not in EXTERNALLY_GENERATED_DOCUMENTS:
                text = path.read_text(encoding="utf-8", errors="replace")
                if text.startswith(GENERATED_MARKER):
                    diagnostics.append(("DOC003", relative.as_posix(), "obsolete generated architecture document exists"))
    return diagnostics


def write_documents(manifest: dict[str, Any], manifest_path: Path) -> list[Path]:
    architecture_root = manifest_path.parent
    expected = render_documents(manifest)
    for relative in expected:
        destination = architecture_root / relative
        if destination.exists() and not destination.read_text(encoding="utf-8", errors="replace").startswith(GENERATED_MARKER):
            raise FileExistsError(f"refusing to overwrite non-generated document: {destination}")
    written: list[Path] = []
    for relative, content in expected.items():
        destination = architecture_root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8", newline="\n")
        written.append(destination)
    generated_root = architecture_root / "generated"
    if generated_root.is_dir():
        for path in generated_root.rglob("*.md"):
            relative = path.relative_to(architecture_root)
            if relative not in expected and relative not in EXTERNALLY_GENERATED_DOCUMENTS:
                text = path.read_text(encoding="utf-8", errors="replace")
                if text.startswith(GENERATED_MARKER):
                    path.unlink()
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, type=Path)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        manifest = load_manifest(args.manifest)
        if args.write:
            for path in write_documents(manifest, args.manifest):
                print(path)
            return 0
        diagnostics = compare_documents(manifest, args.manifest)
        for rule_id, location, message in diagnostics:
            print(f"MUST {rule_id} {location}: {message}")
        print("PASS" if not diagnostics else "FAIL")
        return 0 if not diagnostics else 1
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    print(
        "ERROR: direct legacy CLI removed; use architecture_cli.py gate instead.",
        file=sys.stderr,
    )
    raise SystemExit(2)
