from __future__ import annotations
from datetime import datetime
from typing import Protocol
from thesis_trace.modules.access.session_management.contracts import AccessSession

class SessionRepositoryPort(Protocol):
    def save_session(self, session: AccessSession, token_digest: str) -> None: ...
    def save_recovery_session(self, session: AccessSession, token_digest: str, reason: str, policy_version: str) -> None: ...
    def revoke_recovery_sessions(self, actor_id: str, reason: str, policy_version: str, when: datetime) -> int: ...
    def get_session(self, token_digest: str) -> AccessSession | None: ...
    def revoke_session(self, session_id: str, when: datetime) -> None: ...
